package com.irfangujjar.tmdb.core.ui.util


enum class LanguageCode(val code: String, val englishName: String) {
    AA("aa", "Afar"),
    AB("ab", "Abkhazian"),
    AF("af", "Afrikaans"),
    AK("ak", "Akan"),
    AM("am", "Amharic"),
    AN("an", "Aragonese"),
    AR("ar", "Arabic"),
    AS("as", "Assamese"),
    AV("av", "Avaric"),
    AE("ae", "Avestan"),
    AY("ay", "Aymara"),
    AZ("az", "Azerbaijani"),
    BA("ba", "Bashkir"),
    BM("bm", "Bambara"),
    BE("be", "Belarusian"),
    BN("bn", "Bengali"),
    BI("bi", "Bislama"),
    BO("bo", "Tibetan"),
    BS("bs", "Bosnian"),
    BR("br", "Breton"),
    BG("bg", "Bulgarian"),
    CA("ca", "Catalan"),
    CS("cs", "Czech"),
    CH("ch", "Chamorro"),
    CE("ce", "Chechen"),
    CU("cu", "Church Slavic"),
    CV("cv", "Chuvash"),
    KW("kw", "Cornish"),
    CO("co", "Corsican"),
    CR("cr", "Cree"),
    CY("cy", "Welsh"),
    DA("da", "Danish"),
    DE("de", "German"),
    DV("dv", "Divehi"),
    DZ("dz", "Dzongkha"),
    EL("el", "Greek"),
    EN("en", "English"),
    EO("eo", "Esperanto"),
    ES("es", "Spanish"),
    ET("et", "Estonian"),
    EU("eu", "Basque"),
    EE("ee", "Ewe"),
    FO("fo", "Faroese"),
    FA("fa", "Persian"),
    FJ("fj", "Fijian"),
    FI("fi", "Finnish"),
    FR("fr", "French"),
    FY("fy", "Western Frisian"),
    FF("ff", "Fulah"),
    GA("ga", "Irish"),
    GD("gd", "Scottish Gaelic"),
    GL("gl", "Galician"),
    GV("gv", "Manx"),
    GN("gn", "Guarani"),
    GU("gu", "Gujarati"),
    HT("ht", "Haitian"),
    HA("ha", "Hausa"),
    HE("he", "Hebrew"),
    HZ("hz", "Herero"),
    HI("hi", "Hindi"),
    HO("ho", "Hiri Motu"),
    HR("hr", "Croatian"),
    HU("hu", "Hungarian"),
    HY("hy", "Armenian"),
    IG("ig", "Igbo"),
    IO("io", "Ido"),
    II("ii", "Sichuan Yi"),
    IU("iu", "Inuktitut"),
    IE("ie", "Interlingue"),
    IA("ia", "Interlingua"),
    ID("id", "Indonesian"),
    IK("ik", "Inupiaq"),
    IS("is", "Icelandic"),
    IT("it", "Italian"),
    JV("jv", "Javanese"),
    JA("ja", "Japanese"),
    KL("kl", "Kalaallisut"),
    KN("kn", "Kannada"),
    KS("ks", "Kashmiri"),
    KA("ka", "Georgian"),
    KR("kr", "Kanuri"),
    KK("kk", "Kazakh"),
    KM("km", "Central Khmer"),
    KI("ki", "Kikuyu"),
    RW("rw", "Kinyarwanda"),
    KY("ky", "Kirghiz"),
    KV("kv", "Komi"),
    KG("kg", "Kongo"),
    KO("ko", "Korean"),
    KJ("kj", "Kuanyama"),
    KU("ku", "Kurdish"),
    LO("lo", "Lao"),
    LA("la", "Latin"),
    LV("lv", "Latvian"),
    LI("li", "Limburgan"),
    LN("ln", "Lingala"),
    LT("lt", "Lithuanian"),
    LB("lb", "Luxembourgish"),
    LU("lu", "Luba-Katanga"),
    LG("lg", "Ganda"),
    MK("mk", "Macedonian"),
    MH("mh", "Marshallese"),
    ML("ml", "Malayalam"),
    MI("mi", "Maori"),
    MR("mr", "Marathi"),
    MS("ms", "Malay"),
    MG("mg", "Malagasy"),
    MT("mt", "Maltese"),
    MN("mn", "Mongolian"),
    NA("na", "Nauru"),
    NV("nv", "Navajo"),
    NR("nr", "South Ndebele"),
    ND("nd", "North Ndebele"),
    NG("ng", "Ndonga"),
    NE("ne", "Nepali"),
    NN("nn", "Norwegian Nynorsk"),
    NB("nb", "Norwegian Bokmål"),
    NO("no", "Norwegian"),
    NY("ny", "Chichewa"),
    OC("oc", "Occitan"),
    OJ("oj", "Ojibwa"),
    OR("or", "Oriya"),
    OM("om", "Oromo"),
    OS("os", "Ossetian"),
    PA("pa", "Panjabi"),
    PI("pi", "Pali"),
    PL("pl", "Polish"),
    PT("pt", "Portuguese"),
    PS("ps", "Pashto"),
    QU("qu", "Quechua"),
    RM("rm", "Romansh"),
    RO("ro", "Romanian"),
    RN("rn", "Rundi"),
    RU("ru", "Russian"),
    SG("sg", "Sango"),
    SA("sa", "Sanskrit"),
    SI("si", "Sinhala"),
    SK("sk", "Slovak"),
    SL("sl", "Slovenian"),
    SE("se", "Northern Sami"),
    SM("sm", "Samoan"),
    SN("sn", "Shona"),
    SD("sd", "Sindhi"),
    SO("so", "Somali"),
    ST("st", "Southern Sotho"),
    ES_ALT("es-419", "Spanish (Latin America)"),
    SR("sr", "Serbian"),
    SS("ss", "Swati"),
    SU("su", "Sundanese"),
    SV("sv", "Swedish"),
    SW("sw", "Swahili"),
    TA("ta", "Tamil"),
    TE("te", "Telugu"),
    TG("tg", "Tajik"),
    TH("th", "Thai"),
    TI("ti", "Tigrinya"),
    TK("tk", "Turkmen"),
    TL("tl", "Tagalog"),
    TN("tn", "Tswana"),
    TO("to", "Tonga"),
    TR("tr", "Turkish"),
    TS("ts", "Tsonga"),
    TT("tt", "Tatar"),
    TW("tw", "Twi"),
    TY("ty", "Tahitian"),
    UG("ug", "Uighur"),
    UK("uk", "Ukrainian"),
    UR("ur", "Urdu"),
    UZ("uz", "Uzbek"),
    VE("ve", "Venda"),
    VI("vi", "Vietnamese"),
    VO("vo", "Volapük"),
    WA("wa", "Walloon"),
    WO("wo", "Wolof"),
    XH("xh", "Xhosa"),
    YI("yi", "Yiddish"),
    YO("yo", "Yoruba"),
    ZA("za", "Zhuang"),
    ZH("zh", "Chinese"),
    ZU("zu", "Zulu");

    companion object {
        private val map = entries.associateBy { it.code.lowercase() }
        fun fromCode(code: String): String = map[code.lowercase()]?.englishName ?: "Other"
    }
}